### ISSUE TITLE
pom xml в gitignore

### ISSUE THREAD

**Issue by green-ghost** [Kseniyapa/FinalGroupProject#3]
https://github.com/Kseniyapa/FinalGroupProject/blob/97bc71accf1585c82afc4cad8c4624b45586403d/.gitignore#L1
А зачем в списке игнорирования pom.xml?

**Comment by Kseniyapa** [comment]
Здравствуйте) все исправим, спасибо. 



Отправлено из мобильной Почты Mail.ru


вторник, 7 июля 2020 г., 11:14 +0300 от notifications@github.com  <notifications@github.com>:
